--TB_BOOK테이블 생성

CREATE TABLE TB_BOOK(

	BOOK_NO NUMBER CONSTRAINT TB_BOOK_PK PRIMARY KEY,
	BOOK_TITLE VARCHAR2(50) NOT NULL,
	BOOK_AUTHOR VARCHAR2(50) NOT NULL,
	BOOK_PUB VARCHAR2(50) NOT NULL,
	BOOK_CATE VARCHAR(20) NOT NULL,
	BOOK_STOCK NUMBER
);

COMMENT ON COLUMN TB_BOOK.BOOK_NO 			IS '도서 번호';
COMMENT ON COLUMN TB_BOOK.BOOK_TITLE  	IS '제목';
COMMENT ON COLUMN TB_BOOK.BOOK_AUTHOR 	IS '저자';
COMMENT ON COLUMN TB_BOOK.BOOK_PUB 			IS '출판사';
COMMENT ON COLUMN TB_BOOK.BOOK_CATE 		IS '카테고리';
COMMENT ON COLUMN TB_BOOK.BOOK_STOCK 		IS '재고수량';

-- 샘플 데이터 추가

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (1, '자바의 정석', '남궁성', '도우출판', '프로그래밍', 2);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (2, '파이썬 코딩의 기술', '브렛 슬라킨','길벗', '프로그래밍', 5);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (3, '해리 포터와 마법사의 돌', 'J.K. 롤링', '아카넷', '소설', 8);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (4, '부자 아빠 가난한 아빠', '로버트 기요사키', '영진닷컴', '자기계발', 12);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (5, '1984', '조지 오웰', '민음사', '소설', 7);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (6, '사피엔스', '유발 하라리', '김영사', '역사', 9);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (7, '노인과 바다', '어니스트 헤밍웨이', '시공사', '소설', 6);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (8, '트와일라잇', '스테파니 메이어', '예스24', '소설', 11);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (9, '오만과 편견', '제인 오스틴', '문학수첩', '소설', 8);

INSERT INTO TB_BOOK (BOOK_NO, BOOK_TITLE, BOOK_AUTHOR, BOOK_PUB, BOOK_CATE, BOOK_STOCK)
VALUES (10, '죄와 벌', '피오도르 도스토옙스키', '세계문학사', '소설', 5);


SELECT * FROM TB_BOOK;

COMMIT;





